brokerClusterName = DefaultCluster
brokerName = broker-a
brokerId = 0
deleteWhen = 04
fileReservedTime = 48
brokerRole = ASYNC_MASTER
flushDiskType = ASYNC_FLUSH

namesrvAddr = rocketmq-namesrv:9876
brokerIP1 = rocketmq-broker
listenPort = 10911
haListenPort = 10912
fastListenPort = 10909

storePathRootDir = /home/rocketmq/store
storePathCommitLog = /home/rocketmq/store/commitlog
storePathConsumeQueue = /home/rocketmq/store/consumequeue
storePathIndex = /home/rocketmq/store/index

maxMessageSize = 65536
flushCommitLogLeastPages = 4
flushCommitLogThoroughInterval = 10000
flushConsumeQueueLeastPages = 2
flushConsumeQueueThoroughInterval = 60000
messageDelayLevel = 1s 5s 10s 30s 1m 2m 3m 4m 5m 6m 7m 8m 9m 10m 20m 30m 1h 2h

autoCreateTopicEnable = true
autoCreateSubscriptionGroup = true

traceTopicEnable = true
