global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'core-ledger-account'
    metrics_path: '/account/actuator/prometheus'
    static_configs:
      - targets: ['core-ledger-account:8081']
    scrape_interval: 5s
    scrape_timeout: 5s

  - job_name: 'nacos'
    metrics_path: '/nacos/actuator/prometheus'
    static_configs:
      - targets: ['nacos:8848']

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql:9104']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:9121']

  - job_name: 'seata'
    metrics_path: '/seata/metrics'
    static_configs:
      - targets: ['seata:9848']

  - job_name: 'rocketmq'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['rocketmq-broker:5557']

  - job_name: 'skywalking'
    metrics_path: '/v3/metrics'
    static_configs:
      - targets: ['skywalking-oap:1234']
